language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"

install:
  - pip install pycodestyle
  - pip install coverage
  - pip install codecov

script:
  - coverage run ./setup.py test
  - pycodestyle openfoodfacts/*.py

notifications:
  slack: openfoodfacts:kVMm929AwnFUHXzB8UXU01gG

after_success:
  - codecov
