#----------------------------------------------
# Generate and upload documentation (only on push to develop)
#----------------------------------------------

name: Generate documentation
on:
  push:
    branches:
      - develop
      - Generate-Automatic-documentation

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Install dependencies
        run: pip install requirements.txt

      - name: Generate documentation
        run: bash ./build_mkdocs.sh

    # Deploy docs to gh_pages
    # Example from https://github.com/marketplace/actions/deploy-to-github-pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: gh_pages # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
