name: Publish PyPI Package

on:
  # Triggers the workflow on a new release
  push:
    branches: [actions-dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2.4.0
    - name: Setup Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.8
    - name: Install dependencies
      run: |
        rm -rf dist build *.egg-info
        python3 -m pip install --upgrade pip
        pip install twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        TWINE_REPOSITORY: testpypi
      run: |
        python3 setup.py sdist bdist_wheel
        sudo python3 -m twine upload --non-interactive dist/*  
